FROM nginx:1.15.0-alpine

RUN apk update && apk add curl

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/

RUN mkdir -p /var/www/html/ && \
    touch /var/www/html/index.php